### PR TITLE
Feature load_compiled

### PR DESCRIPTION
**Pull request by jvanasco**
This is more of a request for review than a proper PR, to handle cacheable templates (as in #18). 

The background is that dust javascript handles the caching of template code, and ashes could probably benefit as well.  guess what -- it does.

The approach is simple- AST or python (string/compiled) versions of templates can be extracted and new templates generated from them.  This allows new Ashes Envs/loaders to be created as needed (one per request, etc) from cached versions of the underlying data.

There are 2 files that illustrate this in action:

* tests_jv.py -- raw speed comparison of different template loading strategies
* tests_jv_loader.py -- example of how to load templates via different mechanisms

I fully documented everything inline.  A few changes were made to the inner workings (just splitting out some functionality into multiple methods that are re-usable and making public versions of some private functions). 

After playing around with this I realized that the various load functions need to be in both `AshesEnv` and the base `Template` class.  

So I ended up with these new functions 

Template
* from_ast (classmethod, like `from_path`)
* from_python_string (classmethod, like `from_path`)
* from_python_compiled (classmethod, like `from_path`)
* to_ast
* topython_string

BaseAshesEnv
* generate_ast
* generate_python_string
* load_template_ast
* load_template_python_string
* load_template_python_compiled

There are also some new support functions

* ashes.compile_python_string -- public interface to `ashes._python_compile`
* Template._ast_to_render_func -- split out from `Template._get_render_func`

In terms of performance...  the parsing and compiling functions are fairly expensive!

According to one suite of tests...

* caching the AST saves around 35% of execution time.
* caching the python string representation saves about 65% of execution time
* caching the python function itself and rebuilding templates off that saves 96% of execution time (!).  this approach won't work in a lot of situations, but if it works in your environment -- wow.

### CODE REVIEW

**Comment by mahmoud** [comment]
Initial review looks pretty sound so far! Any thoughts on invalidation/when to reload?

**Comment by jvanasco** [comment]
Not really.  What are the normal situations that occurs?  Shouldn't be too hard to factor in.

**Comment by mahmoud** [comment]
I guess I just mean, do you project that [this](https://github.com/mahmoud/ashes/blob/master/ashes.py#L1736) and [this](https://github.com/mahmoud/ashes/blob/master/ashes.py#L1911-L1914) will continue to work as usual with the compiled caches?

Also, I'd like to see the test templates used to be more realistic in terms of complexity. Here's one that gets pretty good feature coverage: https://github.com/mahmoud/chert/blob/master/chert/scaffold/theme/base.html

**Comment by jvanasco** [comment]
Oh!  Great points all around.  Will address most tomorrow.

I didn't think it should handle the source's modified time, as I was approaching this from the js point of view (where sources are compiled once then distributed).  I was also thinking about this from compiling strings, not files.

Thinking about this from a python pov, mako and other packages support an option to compile once and cache based on the mtime.  That might be a good option to implement.

**Comment by jvanasco** [comment]
rescinding for a new PR

**Pull request closed without merging**
