### PR TITLE
Feature compiled slimmer

### PR DESCRIPTION
**Pull request by jvanasco**
This is replacing PR #32.  All the args to __init__ were removed in favor of only using class methods like the existing `from_path`.  This sidestepped a negligible performance issue, but looks much cleaner. 

-----

I added a changelog that goes through everything, but here's the topline overview:

* i updated the run_tests to have two new commands: benchmarks and unittests.
 * the unittests use unittest to test the API methods for roundtrips (and potentially other things).  
 * benchmarks run profiling on the baseline Chert files, a second routine benches the different cache methods

* i was wrong. after doing some profiling and testing with possible cache techniques, the most aggressive way to cache Ashes templates is to `marshal` the generated code objects (before being run through `exec`).  that has a negligible performance hit -- only running at 125% the time of re-used environment (re-using the python string runs around 450% the time)

There are a few points for concern/review:

1. I changed `_get_render_func` to return a tuple of (code, func) objects.   The func is stashed on the object, the code is not (originally it was, but there is no need and clearing it out is a bit leaner).
2. I replaced `_get_render_func(str=true) with it's own function.  It was only called by a test and was not a public method.

### CODE REVIEW

**Comment by mahmoud** [comment]
Finally getting back to reviewing this. Amazing work. Especially with the tests and extracting stuff from Chert, which I know couldn't have been totally trivial :). I may have some updates to docs, etc., for after merge, but this looks great to me. It seems like you're still doing some incremental improvements, so just let me know when's a good time to merge and I'll hit that green button so fast :)

**Comment by jvanasco** [comment]
Thanks!  This PR is done and ready to review.  I only redid it after integrating the fork and realizing there were some edge cases (So fixed and wrote tests).

I could supply docs for writing unit tests if you'd like.  The only hard thing was writing the test fixtures into the same suite without disturbing the existing tests. This was my third approach on it.

I've been playing around on a new branch with possibly updates for the cpython interpreter, but nothing worth pushing yet.  During profiling I noticed there are a handful of functions that are called hundreds of times per "page" render (if you use partials), so there may be improvements via eliminating dots or pushing global into locals.

**Comment by jvanasco** [comment]
FYI, I can merge in the profiling code if you're interested. It's basically done in two components:

1. Another test in benchmarks that just `renders` the same template in a global env (the current one builds a new env/loader per iteration)
2. A `tests/utils_profiling` package that is mostly lifted from pyramid's debugtoolbar.  it runs an invoked function through python's profiler, and then formats/exports the data into a CSV file (I like using Excel).

I targeted whatever had the most calls or largest size for possible changes.  The filters seem to be one of the best place for improvements, but the only measurable improvement I could find was pretty small and not worth issuing another PR.

    def _escape_html_factory():
        """
        slightly optimized for the cPython interpreter.
        this turns the constant lookup for global cgi + attribute escape
        into a local cgi_escape variable (inspired by simplejson; thanks bob).
        """
        def escape_html(text, cgi_escape=cgi.escape):
            text = to_unicode(text)
            # TODO: dust.js doesn't use this, but maybe we should:
            # .replace("'", '&squot;')
            return cgi_escape(text, True)
        return escape_html
    escape_html = _escape_html_factory()

`escape_uri_component` will run about 2x as fast if replaced with a regex pattern sub, but it's rarely used.

**Comment by mahmoud** [comment]
That's great! Let's have a separate PR for more profiling code. Merging this now.

**Pull request merged**
